mongodb:
  image: mongo
  expose:
    - 27017

townhall:
  build: ./townhall
  environment:
    MONGO_URL: mongodb://mongodb:27017
    PYTHONPATH: /opt/ansible/ansible/lib:/townhall/ansible-townhall
  ports:
    - "8080:8080"
  links:
    - mongodb
